// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWm3_Md8E8BSxmO2SVlNThb_jd7g3GJZA',
    appId: '1:156348170168:web:46c749b7d3f68644e9994d',
    messagingSenderId: '156348170168',
    projectId: 'embeddedclub',
    authDomain: 'embeddedclub.firebaseapp.com',
    storageBucket: 'embeddedclub.appspot.com',
    measurementId: 'G-20KW4F5L97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcK0w2HRDfQeM2h2ySV61wIvy_6H1yEQ',
    appId: '1:156348170168:android:5ec7f596a9e314f4e9994d',
    messagingSenderId: '156348170168',
    projectId: 'embeddedclub',
    storageBucket: 'embeddedclub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs7LBumGmeaib8hiM5Iv19gQ0mIG7f-3A',
    appId: '1:156348170168:ios:83b36ad8bee376bae9994d',
    messagingSenderId: '156348170168',
    projectId: 'embeddedclub',
    storageBucket: 'embeddedclub.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs7LBumGmeaib8hiM5Iv19gQ0mIG7f-3A',
    appId: '1:156348170168:ios:0fd09ca81e3f32e7e9994d',
    messagingSenderId: '156348170168',
    projectId: 'embeddedclub',
    storageBucket: 'embeddedclub.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
